### ISSUE TITLE
Should Nectar assume the width of a thumbnail?

### ISSUE THREAD

**Issue by markpbaggett** [samvera-labs/nectar-iiif#15]
At UTK, we don't necessarily have a set size for thumbnails.  Our current practice is to generate thumbnails that are at least `400` pixels wide.  That being said, Nectar always takes whatever the thumbnail is and degrades it to `200` pixels wide in `useGetImageResource`. This has several negative effects in my opinion.

1. You can't use your thumbnail in its native size. It will always be downsize to 200 pixels.
2. If you're using something like Bloom that leverages Nectar, it too follows this same practice. This can lead to some weirdness since Bloom initially will make use of the thumbnail associated with an item in the collection in its native state and then onHover reduce that thumbnail to `200` pixels wide.

In my opinion, nectar should leverage the `width` property from `resource` and pass it with `service` since it is a required property in [2.0](https://iiif.io/api/image/2.0/#image-information), [2.1](https://iiif.io/api/image/2.1/#technical-properties), and [3.0](https://iiif.io/api/image/3.0/#52-technical-properties).

```
if (Array.isArray(resource.service) && resource.service.length > 0)
    imageService = service[0] as ImageService;
```

Is there any reason why `width` should not be leveraged from `resource` and used in place of `size` here?

```
  if (imageService) {
    if (imageService["@id"])
      return `${imageService["@id"]}/${region}/${size}/0/default.jpg`;

    if (imageService.id)
      return `${imageService.id}/${region}/${size}/0/default.jpg`;
  }
```

**Comment by mathewjordan** [comment]
Addressed by https://github.com/samvera-labs/nectar-iiif/pull/16
